export const MUNICIPIOS_MONAGAS = [
  'MATURÍN', 'ACOSTA', 'AGUASAY', 'BOLÍVAR', 'CARIPE', 'CEDEÑO',
  'EZEQUIEL ZAMORA', 'LIBERTADOR', 'PIAR', 'PUNCERES', 'SANTA BÁRBARA',
  'SOTILLO', 'URACOA', 'SAN SIMÓN'
]

export const DEPENDENCIAS = ['NACIONAL', 'ESTADAL', 'PRIVADO', 'SUBVENCIONADO', 'AUTÓNOMO']

export const ESTATUS_QR_LIST = ['QR SEGEN', 'SIN QR ASIGNADO', 'REPONER QR']

export const ROLES_LIST = ['DIRECTOR', 'ENLACE_SEGEN', 'SUPERVISOR', 'REPRESENTANTE']

export const TIPO_SOLICITUD_LIST = ['REPOSICION', 'NUEVA_ASIGNACION', 'CORRECCION']

export const ESTATUS_SOLICITUD_LIST = ['PENDIENTE', 'PROCESADO', 'COMPLETADO']
